# Using Pandas

In [1]:
pwd

'C:\\Users\\atycn\\OneDrive\\Dokumente\\GitHub\\Iron_Adam\\Pandas'

In [2]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 200)
## to make it possible to display multiple output inside one cell 
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

<b>load the data from the vehicles.csv file into pandas data frame

In [3]:
## Your Code here

cars = pd.read_csv("vehicles.csv")

cars

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150

First exploration of the dataset:

- How many observations does it have?
- Look at all the columns: do you understand what they mean?
- Look at the raw data: do you see anything weird?
- Look at the data types: are they the expected ones for the information the column contains?

In [4]:
## Your Code here

# Number of observations

cars.shape

(35952, 15)

### Cleaning and wrangling data

- Some car brand names refer to the same brand. Replace all brand names that contain the word "Dutton" for simply "Dutton". If you find similar examples, clean their names too. Use `loc` with boolean indexing.

- Convert CO2 Emissions from Grams/Mile to Grams/Km

- Create a binary column that solely indicates if the transmission of a car is automatic or manual. Use `pandas.Series.str.startswith` and .

- convert MPG columns to km_per_liter

In [5]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35952 entries, 0 to 35951
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Make                     35952 non-null  object
 1   Model                    35952 non-null  object
 2   Year                     35952 non-null  int64
 3   Engine Displacement      35952 non-null  float64
 4   Cylinders                35952 non-null  float64
 5   Transmission             35952 non-null  object
 6   Drivetrain               35952 non-null  object
 7   Vehicle Class            35952 non-null  object
 8   Fuel Type                35952 non-null  object
 9   Fuel Barrels/Year        35952 non-null  float64
 10  City MPG                 35952 non-null  int64
 11  Highway MPG              35952 non-null  int64
 12  Combined MPG             35952 non-null  int64
 13  CO2 Emission Grams/Mile  35952 non-null  float64
 14  Fuel Cost/Year           35952 non-null  int64
dtypes: float64(4), int64(5), object(6)
memory usage: 4.1+ MB

In [6]:
## Your Code here

# Replacing items containing the string "Dutton" in the column "Make" with "Dutton"

cars["Make"][cars["Make"].str.contains("Dutton")] = "Dutton"

C:\Users\atycn\AppData\Local\Temp/ipykernel_18252/2646461846.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cars["Make"][cars["Make"].str.contains("Dutton")] = "Dutton"

In [7]:
cars["Make"].str.contains("Dutton")

0        False
1        False
2        False
3        False
4        False
         ...
35947    False
35948    False
35949    False
35950    False
35951    False
Name: Make, Length: 35952, dtype: bool

In [8]:
cars

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150

In [9]:
# Convert CO2 Emissions from Grams/Mile to Grams/Km
cars.rename(columns = {"CO2 Emission Grams/Mile":"CO2 Emission Grams/Km"}, inplace = True)

In [10]:
cars["CO2 Emission Grams/Km"] = cars["CO2 Emission Grams/Km"] / 1.60934

Converting Grams/Mile to Grams/Km

1 Mile = 1.60934 Km

Grams/Mile * Mile/Km -> Grams/Mile * 1 Mile/1.60934Km

$$ \frac{Grams}{Mile} * \frac{Mile}{Km} $$

$$ \frac{Grams}{Mile} * \frac{1 Mile}{1.60934Km}  $$

convert MPG columns to km_per_liter

MPG = Miles/Gallon -> Km/Liter

1 Mile = 1.60934 Km

1 Gallon = 3.78541 Liters

$$ \frac{Miles}{Gallon} -> \frac{Miles}{Gallon} * \frac{Km}{Miles} * \frac{Gallon}{Liters}$$

$$ \frac{Miles}{Gallon} -> \frac{Miles}{Gallon} * \frac{1.60934Km}{ 1Miles} * \frac{1 Gallon}{3.78541 Liters}$$

* ( 1.60934 / 3.78541 )

### Gathering insights:

- How many car makers are there? How many models? Which car maker has the most cars in the dataset?

- When were these cars made? How big is the engine of these cars?

- What's the frequency of different transmissions, drivetrains and fuel types?

- What's the car that consumes the least/most fuel?

In [11]:
# Create a binary column that solely indicates if the transmission of a car is automatic or manual.

cars["New column"] = cars["Transmission"].map(lambda x : "Automatic" if "Auto" in x else "Manual")
              
cars

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Km,Fuel Cost/Year,New column
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,324.831736,1950,Automatic
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,424.779962,2550,Automatic
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,345.133719,2100,Automatic
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,424.779962,2550,Automatic
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,345.133719,2550,Automatic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,151.614948,1100,Automatic
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,150.993575,1100,Automatic
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,151.614948,1100,Automatic
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,152.857693,1100,Automatic
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,158.450048,1150,Manual

What brand has the worse CO2 Emissions on average?

Hint: use the function `sort_values()`

In [12]:
emissions = cars.groupby(["Make"])["CO2 Emission Grams/Km"].mean()
emissions.sort_values(ascending = False)

Make
Vector                              651.919248
Bugatti                             542.497235
Laforza Automobile Inc              502.012683
Dutton                              476.419879
Rolls-Royce                         475.397772
Lamborghini                         469.001266
Texas Coach Company                 460.178293
Maybach                             453.327003
Ferrari                             442.812798
Bentley                             426.290692
Ruf Automobile Gmbh                 424.779962
Tecstar, LP                         424.779962
Aston Martin                        417.946348
Pagani                              416.941106
Saleen Performance                  409.609249
Wallace Environmental               408.857065
Vixen Motor Company                 395.348404
Excalibur Autos                     394.438536
PAS, Inc                            394.438536
J.K. Motors                         390.994816
Roush Performance                   386.441107
Maserati                            385.686226
AM General                          379.881345
SRT                                 377.173251
Land Rover                          373.280395
Saleen                              370.923931
JBA Motorcars, Inc.                 368.142634
PAS Inc - GMC                       368.142634
Panos                               368.142634
CCC Engineering                     368.142634
Aurora Cars Ltd                     368.142634
Hummer                              365.374644
Spyker                              361.479419
Federal Coach                       360.588086
Import Trade Services               356.214289
GMC                                 355.109034
VPG                                 355.006336
Bitter Gmbh and Co. Kg              352.803358
BMW Alpina                          352.803358
Environmental Rsch and Devp Corp    345.133719
London Coach Co Inc                 345.133719
ASC Incorporated                    345.133719
Dodge                               344.554180
CX Automotive                       343.312774
Mobility Ventures LLC               340.201573
Dabryan Coach Builders Inc          339.268702
Autokraft Limited                   334.982728
Bill Dovell Motor Car Company       324.831736
Lambda Control Systems              324.831736
Morgan                              324.831736
Grumman Allied Industries           324.831736
Shelby                              324.831736
Ford                                320.296589
Chevrolet                           318.564940
Mahindra                            316.278723
American Motors Corporation         314.264744
Mercedes-Benz                       311.421545
Jeep                                309.928716
Cadillac                            308.375552
Goldacre                            306.785528
General Motors                      306.785528
TVR Engineering Ltd                 306.785528
Jaguar                              306.582116
Merkur                              305.387965
Isuzu                               305.229090
Sterling                            304.252727
McLaren Automotive                  303.981385
Lincoln                             302.572997
Ram                                 298.360841
Peugeot                             291.565042
Evans Automobiles                   290.638922
Import Foreign Auto Sales Inc       290.638922
Volga Associated Automobile         290.638922
Genesis                             288.405717
Alfa Romeo                          288.287195
Porsche                             288.199235
London Taxi                         287.526112
Infiniti                            286.982449
BMW                                 284.262087
Nissan                              283.443767
Mcevoy Motors                       280.950958
Audi                                280.087391
Chrysler                            277.609760
Lotus                               276.195577
Isis Imports Ltd                    276.106976
Saab                                275.571531
Lexus                               275.240120
Oldsmobile                          273.849170
Panther Car Company Limited         272.819988
Mercury                             271.489475
Pininfarina                         270.822632
Volvo                               270.796572
Toyota                              270.791631
Buick                               269.963993
Mitsubishi                          268.105004
Qvale                               262.959024
Consulier Industries Inc            262.959024
Quantum Technologies                262.959024
Acura                               262.583000
Mazda                               261.798342
Plymouth                            259.018217
Pontiac                             257.513762
Eagle                               255.476174
Subaru                              251.230978
Bertone                             251.006341
Panoz Auto-Development              251.006341
Suzuki                              244.042612
Volkswagen                          244.038998
Kia                                 242.732303
Daewoo                              240.941937
Red Shift Ltd.                      240.093022
Dacia                               240.093022
Hyundai                             239.241983
Saturn                              233.832051
Renault                             223.586374
Honda                               222.160996
Grumman Olson                       221.418360
Yugo                                221.251107
Geo                                 209.450825
Scion                               205.920389
MINI                                194.935105
Daihatsu                            192.742404
Fiat                                189.311494
smart                               153.498052
Fisker                              105.011992
Name: CO2 Emission Grams/Km, dtype: float64

Do cars with automatic transmission consume more fuel than cars with manual transmission on average?

In [13]:
## Your Code is here 
fuel_cons = cars.groupby(["New column"])["Fuel Barrels/Year"].mean()
fuel_cons

New column
Automatic    18.043152
Manual       16.704904
Name: Fuel Barrels/Year, dtype: float64

In [14]:
cars.to_csv("cars.csv")